variable "count" {
description = "(Required) This will enable event_rule module"
default = {}
}



variable "description" {
default = ""
}

variable "target_id" {
description = "(required) target ID will be generated by terraform if hadnt provide in target. but if you are using event rule console you need to add target ID on existing resource"
default = ""
}

variable "target_arn" {
default = ""
}

variable "event_pattern" {
default = ""
}

variable "rule" {
default = ""
}

variable "dashboard_name" {
default = ""
}

variable "dashboard_body" {
default = ""
}




variable "name" {
description  = "(Required) The descriptive name for the alarm. This name must be unique within the user's AWS account"
default = ""
}

variable "count_metric_alert" {
description = "(Required) This will enable metric alert module module"
default = 0
}

variable "comparison_operator" {
description = "- (Required) The arithmetic operation to use when comparing the specified Statistic and Threshold. The specified Statistic value is used as the first operand. Either of the following is supported: GreaterThanOrEqualToThreshold, GreaterThanThreshold, LessThanThreshold, LessThanOrEqualToThreshold."
type = "map"
default = {
GreaterThanOrEqualToThreshold = "GreaterThanOrEqualToThreshold"

}
}

variable "evaluation_periods" {
description = "(Required) The number of periods over which data is compared to the specified threshold."
type = "map"
default = {
evaluation_periods = "3"
}
}

variable "metric_name" {
description = "(Required) The name for the alarm's associated metric. For reference: https://goo.gl/u3VeRN"
default = ""
}

variable "namespace" {
description = "(Required) The namespace for the alarm's associated metric. See docs for the list of namespaces. For reference: https://goo.gl/u3VeRN"
default = ""
}

variable "period" {
description = "(Required) The period in seconds over which the specified statistic is applied."
type = "map"
default = {
period = "300"
}
}

variable "statistic" {
description = "(Optional) The statistic to apply to the alarm's associated metric. Either of the following is supported: SampleCount, Average, Sum, Minimum, Maximum"
default = ""
}

variable "threshold" {
description = "(Required) The value against which the specified statistic is compared."
type = "map"
default = {
threshold = "20"
}
}

variable "alarm_description" {
description = "(Optional) The description for the alarm."
default = ""
}

variable "ok_actions" {
description = "(Optional) The list of actions to execute when this alarm transitions into an OK state from any other state. Each action is specified as an Amazon Resource Number (ARN)."
default = ""
}

variable "alarm_actions" {
description = " (Optional) The list of actions to execute when this alarm transitions into an ALARM state from any other state. Each action is specified as an Amazon Resource Number (ARN)."
default = []
}

variable "actions_enabled" {
description = "(Optional) Indicates whether or not actions should be executed during any changes to the alarm's state. Defaults to true."
default = ""
}

variable "unit" {
description = "(Optional) The unit for the alarm's associated metric."
default = {}
}

variable "treat_missing_data" {
description = "(Optional) Sets how this alarm is to handle missing data points. The following values are supported: missing, ignore, breaching and notBreaching. Defaults to missing."
default = ""
}

variable "insufficient_data_actions" {
description = "(Optional) The list of actions to execute when this alarm transitions into an INSUFFICIENT_DATA state from any other state. Each action is specified as an Amazon Resource Number (ARN)."
default = ""
}